slice_name: Comparison of Payment Methods to Payment Value
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 19__table
  viz_type: echarts_timeseries_bar
  slice_id: 11
  x_axis: payment_type
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  x_axis_sort_series: sum
  x_axis_sort_series_ascending: false
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: total_orders
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 160
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: LONGINTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Total Order
    optionName: metric_ncocbwp5k2l_hm05dod9ps
    sqlExpression: null
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: total_payment_value
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 161
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: FLOAT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Payment Value
    optionName: metric_yzos5et3hc8_2uo970ngh5
    sqlExpression: null
  - aggregate: AVG
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: average_payment_value
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 162
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: FLOAT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Averag Payment Value
    optionName: metric_qa21jn1eegh_0hvb20c75p7
    sqlExpression: null
  groupby: []
  adhoc_filters: []
  order_desc: true
  row_limit: 10
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: horizontal
  x_axis_title: ''
  x_axis_title_margin: 15
  y_axis_title: ''
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: googleCategory10c
  show_value: true
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: bottom
  x_axis_time_format: smart_date
  xAxisLabelRotation: 0
  y_axis_format: SMART_NUMBER
  logAxis: false
  minorSplitLine: false
  truncateXAxis: true
  truncateYAxis: false
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":19,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"payment_type","label":"payment_type","expressionType":"SQL"}],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_orders","description":null,"expression":null,"filterable":true,"groupby":true,"id":160,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Total
  Order","optionName":"metric_ncocbwp5k2l_hm05dod9ps","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_payment_value","description":null,"expression":null,"filterable":true,"groupby":true,"id":161,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Payment
  Value","optionName":"metric_yzos5et3hc8_2uo970ngh5","sqlExpression":null},{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"average_payment_value","description":null,"expression":null,"filterable":true,"groupby":true,"id":162,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Averag
  Payment Value","optionName":"metric_qa21jn1eegh_0hvb20c75p7","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_orders","description":null,"expression":null,"filterable":true,"groupby":true,"id":160,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Total
  Order","optionName":"metric_ncocbwp5k2l_hm05dod9ps","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["payment_type"],"columns":[],"aggregates":{"Total
  Order":{"operator":"mean"},"Payment Value":{"operator":"mean"},"Averag Payment Value":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"19__table","viz_type":"echarts_timeseries_bar","slice_id":11,"x_axis":"payment_type","time_grain_sqla":"P1D","x_axis_sort_asc":true,"x_axis_sort_series":"sum","x_axis_sort_series_ascending":false,"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_orders","description":null,"expression":null,"filterable":true,"groupby":true,"id":160,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"LONGINTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Total
  Order","optionName":"metric_ncocbwp5k2l_hm05dod9ps","sqlExpression":null},{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"total_payment_value","description":null,"expression":null,"filterable":true,"groupby":true,"id":161,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Payment
  Value","optionName":"metric_yzos5et3hc8_2uo970ngh5","sqlExpression":null},{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"average_payment_value","description":null,"expression":null,"filterable":true,"groupby":true,"id":162,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Averag
  Payment Value","optionName":"metric_qa21jn1eegh_0hvb20c75p7","sqlExpression":null}],"groupby":[],"adhoc_filters":[],"order_desc":true,"row_limit":10,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"horizontal","x_axis_title":"","x_axis_title_margin":15,"y_axis_title":"","y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"googleCategory10c","show_value":true,"only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"bottom","x_axis_time_format":"smart_date","xAxisLabelRotation":0,"y_axis_format":"SMART_NUMBER","logAxis":false,"minorSplitLine":false,"truncateXAxis":true,"truncateYAxis":false,"y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 2ce8d671-1a9f-4123-ad82-e7f4d9eb836a
version: 1.0.0
dataset_uuid: 67f08945-69e9-42c8-8cfd-c23e2e4d596d
