slice_name: Presentation Order by Category
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 12__table
  viz_type: echarts_timeseries_bar
  slice_id: 5
  x_axis: product_category_name_english
  time_grain_sqla: P1D
  xAxisForceCategorical: true
  x_axis_sort: Order
  x_axis_sort_asc: false
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: order_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 130
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: STRING
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Order
    optionName: metric_8u4c09f9vr_aafultz0ojq
    sqlExpression: null
  groupby: []
  contributionMode: column
  adhoc_filters: []
  order_desc: true
  row_limit: 10
  truncate_metric: true
  show_empty_columns: false
  comparison_type: values
  annotation_layers: []
  forecastEnabled: false
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: horizontal
  x_axis_title: ''
  x_axis_title_margin: 15
  y_axis_title: ''
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  sort_series_ascending: false
  color_scheme: bnbColors
  show_value: true
  stack: null
  only_total: true
  minorTicks: true
  zoomable: false
  show_legend: true
  legendType: scroll
  legendOrientation: bottom
  legendMargin: ''
  x_axis_time_format: smart_date
  xAxisLabelRotation: 0
  y_axis_format: SMART_NUMBER
  logAxis: false
  minorSplitLine: false
  truncateXAxis: true
  truncateYAxis: false
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":12,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"product_category_name_english","label":"product_category_name_english","expressionType":"SQL"}],"metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"order_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":130,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"STRING","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Order","optionName":"metric_8u4c09f9vr_aafultz0ojq","sqlExpression":null}],"orderby":[[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"order_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":130,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"STRING","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Order","optionName":"metric_8u4c09f9vr_aafultz0ojq","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["product_category_name_english"],"columns":[],"aggregates":{"Order":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"contribution","options":{"orientation":"column"}},{"operation":"sort","options":{"by":"Order","ascending":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"12__table","viz_type":"echarts_timeseries_bar","slice_id":5,"x_axis":"product_category_name_english","time_grain_sqla":"P1D","xAxisForceCategorical":true,"x_axis_sort":"Order","x_axis_sort_asc":false,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"order_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":130,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"STRING","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Order","optionName":"metric_8u4c09f9vr_aafultz0ojq","sqlExpression":null}],"groupby":[],"contributionMode":"column","adhoc_filters":[],"order_desc":true,"row_limit":10,"truncate_metric":true,"show_empty_columns":false,"comparison_type":"values","annotation_layers":[],"forecastEnabled":false,"forecastPeriods":10,"forecastInterval":0.8,"orientation":"horizontal","x_axis_title":"","x_axis_title_margin":15,"y_axis_title":"","y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","sort_series_ascending":false,"color_scheme":"bnbColors","show_value":true,"stack":null,"only_total":true,"minorTicks":true,"zoomable":false,"show_legend":true,"legendType":"scroll","legendOrientation":"bottom","legendMargin":"","x_axis_time_format":"smart_date","xAxisLabelRotation":0,"y_axis_format":"SMART_NUMBER","logAxis":false,"minorSplitLine":false,"truncateXAxis":true,"truncateYAxis":false,"y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 031d8fad-bae8-46cd-b40a-a6a0dcca282d
version: 1.0.0
dataset_uuid: c309c7ea-b3e3-4075-bc2e-8e5f9a1f77e5
