slice_name: Product Price
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 5__table
  viz_type: echarts_timeseries_bar
  slice_id: 1
  x_axis: product_category_name_english
  time_grain_sqla: P1D
  xAxisForceCategorical: true
  x_axis_sort: Price
  x_axis_sort_asc: false
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: AVG
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: price
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 51
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: FLOAT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Price
    optionName: metric_x4fh84n0y6_sxc3ephf76
    sqlExpression: null
  groupby: []
  contributionMode: null
  adhoc_filters: []
  order_desc: true
  row_limit: 10
  truncate_metric: true
  show_empty_columns: true
  rolling_type: null
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: horizontal
  x_axis_title: ''
  x_axis_title_margin: 15
  y_axis_title: ''
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: googleCategory10c
  show_value: true
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: bottom
  x_axis_time_format: smart_date
  xAxisLabelRotation: 0
  y_axis_format: SMART_NUMBER
  logAxis: false
  minorSplitLine: false
  truncateXAxis: true
  truncateYAxis: false
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipSortByMetric: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 1
query_context: '{"datasource":{"id":5,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"product_category_name_english","label":"product_category_name_english","expressionType":"SQL"}],"metrics":[{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"price","description":null,"expression":null,"filterable":true,"groupby":true,"id":51,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Price","optionName":"metric_x4fh84n0y6_sxc3ephf76","sqlExpression":null}],"orderby":[[{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"price","description":null,"expression":null,"filterable":true,"groupby":true,"id":51,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Price","optionName":"metric_x4fh84n0y6_sxc3ephf76","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["product_category_name_english"],"columns":[],"aggregates":{"Price":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"sort","options":{"by":"Price","ascending":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"5__table","viz_type":"echarts_timeseries_bar","slice_id":1,"x_axis":"product_category_name_english","time_grain_sqla":"P1D","xAxisForceCategorical":true,"x_axis_sort":"Price","x_axis_sort_asc":false,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"price","description":null,"expression":null,"filterable":true,"groupby":true,"id":51,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Price","optionName":"metric_x4fh84n0y6_sxc3ephf76","sqlExpression":null}],"groupby":[],"contributionMode":null,"adhoc_filters":[],"order_desc":true,"row_limit":10,"truncate_metric":true,"show_empty_columns":true,"rolling_type":null,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"horizontal","x_axis_title":"","x_axis_title_margin":15,"y_axis_title":"","y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"googleCategory10c","show_value":true,"only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"bottom","x_axis_time_format":"smart_date","xAxisLabelRotation":0,"y_axis_format":"SMART_NUMBER","logAxis":false,"minorSplitLine":false,"truncateXAxis":true,"truncateYAxis":false,"y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipSortByMetric":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[1],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 3c460609-89cd-451d-b80f-f2e141f05393
version: 1.0.0
dataset_uuid: 0ae9142d-47a6-46b5-9a7f-40ba181db04a
